FROM mcr.microsoft.com/devcontainers/python:3.10

RUN sudo apt-get update \
    && sudo apt-get upgrade

# RUN git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml

# RUN pip install xformers torch torchvision
